[package]
name = "mail-dev"
version = "0.10.1"
description = "Local SMTP server for email testing and debugging"
authors = ["Franck Hérold TAMTO TAMKO"]
license = "MIT"
repository = "https://github.com/STIFLEUR390/mail-dev"
homepage = "https://github.com/STIFLEUR390/mail-dev"
readme = "../README.md"
keywords = ["smtp", "email", "testing", "mail", "dev-tools"]
default-run = "mail-dev"
edition = "2024"
build = "src/build.rs"

[lib]
name = "mail_dev_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dev-dependencies]
tauri = { version = "2", features = ["test"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
mailin = "0.6"
mailparse = "0.16"
lettre = "0.11"
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-http = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-notification = "2"
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite"] }
tauri-plugin-process = "2.3.1"
sentry = "0.42"
tauri-plugin-sentry = "0.5"

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-updater = "2.10.1"
